//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HomeFoodEntities : DbContext
    {
        public HomeFoodEntities()
            : base("name=HomeFoodEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<MAS_AddressType> MAS_AddressType { get; set; }
        public virtual DbSet<MAS_Category> MAS_Category { get; set; }
        public virtual DbSet<MAS_ChefType> MAS_ChefType { get; set; }
        public virtual DbSet<MAS_City> MAS_City { get; set; }
        public virtual DbSet<MAS_DeliveryLocation> MAS_DeliveryLocation { get; set; }
        public virtual DbSet<MAS_Discount> MAS_Discount { get; set; }
        public virtual DbSet<MAS_DiscountType> MAS_DiscountType { get; set; }
        public virtual DbSet<MAS_Food> MAS_Food { get; set; }
        public virtual DbSet<MAS_FoodType> MAS_FoodType { get; set; }
        public virtual DbSet<MAS_MealPack> MAS_MealPack { get; set; }
        public virtual DbSet<MAS_OrderStatus> MAS_OrderStatus { get; set; }
        public virtual DbSet<MAS_OrderType> MAS_OrderType { get; set; }
        public virtual DbSet<MAS_PaymentType> MAS_PaymentType { get; set; }
        public virtual DbSet<MAS_Price> MAS_Price { get; set; }
        public virtual DbSet<MAS_Rights> MAS_Rights { get; set; }
        public virtual DbSet<MAS_Role> MAS_Role { get; set; }
        public virtual DbSet<Observe> Observes { get; set; }
        public virtual DbSet<TRN_ChefDetails> TRN_ChefDetails { get; set; }
        public virtual DbSet<TRN_ChefOrder> TRN_ChefOrder { get; set; }
        public virtual DbSet<TRN_ChefOtherDetails> TRN_ChefOtherDetails { get; set; }
        public virtual DbSet<TRN_DeliveryDetails> TRN_DeliveryDetails { get; set; }
        public virtual DbSet<TRN_GroupRights> TRN_GroupRights { get; set; }
        public virtual DbSet<TRN_MapOrderToChef> TRN_MapOrderToChef { get; set; }
        public virtual DbSet<TRN_MealPackMapping> TRN_MealPackMapping { get; set; }
        public virtual DbSet<TRN_MealPackProcessing> TRN_MealPackProcessing { get; set; }
        public virtual DbSet<TRN_Order> TRN_Order { get; set; }
        public virtual DbSet<TRN_OrderAppliedDiscount> TRN_OrderAppliedDiscount { get; set; }
        public virtual DbSet<TRN_OrderDetails> TRN_OrderDetails { get; set; }
        public virtual DbSet<TRN_SpecialDiscount> TRN_SpecialDiscount { get; set; }
        public virtual DbSet<TRN_UserAddressDetails> TRN_UserAddressDetails { get; set; }
        public virtual DbSet<TRN_UserDetail> TRN_UserDetail { get; set; }
        public virtual DbSet<TRN_UserPassword> TRN_UserPassword { get; set; }
        public virtual DbSet<TRN_UserRights> TRN_UserRights { get; set; }
    }
}
