//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Food
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_Food()
        {
            this.MAS_Discount = new HashSet<MAS_Discount>();
            this.MAS_Price = new HashSet<MAS_Price>();
            this.TRN_MealPackMapping = new HashSet<TRN_MealPackMapping>();
            this.TRN_OrderDetails = new HashSet<TRN_OrderDetails>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int FoodId { get; set; }
        public string FoodName { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> FoodTypeID { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_Category MAS_Category { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_Discount> MAS_Discount { get; set; }
        public virtual MAS_FoodType MAS_FoodType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_Price> MAS_Price { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_MealPackMapping> TRN_MealPackMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_OrderDetails> TRN_OrderDetails { get; set; }
    }
}
