//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_MealPack
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_MealPack()
        {
            this.TRN_MealPackMapping = new HashSet<TRN_MealPackMapping>();
            this.TRN_MealPackProcessing = new HashSet<TRN_MealPackProcessing>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int MealPackId { get; set; }
        public string MealPackName { get; set; }
        public string Descriptions { get; set; }
        public int TotalMealCount { get; set; }
        public int CurrentMealCount { get; set; }
        public int CurrentPrice { get; set; }
        public int TotalPrice { get; set; }
        public int GSTPrice { get; set; }
        public int GSTPercentage { get; set; }
        public int OrderTypeId { get; set; }
        public Nullable<int> OrderTypeCode { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_OrderType MAS_OrderType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_MealPackMapping> TRN_MealPackMapping { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_MealPackProcessing> TRN_MealPackProcessing { get; set; }
    }
}
