//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_FoodType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_FoodType()
        {
            this.MAS_Food = new HashSet<MAS_Food>();
            this.TRN_ChefOtherDetails = new HashSet<TRN_ChefOtherDetails>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int FoodTypeID { get; set; }
        public string FoodType { get; set; }
        public Nullable<int> FoodTypeCode { get; set; }
        public bool IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MAS_Food> MAS_Food { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_ChefOtherDetails> TRN_ChefOtherDetails { get; set; }
    }
}
