//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_Area
    {
        public System.Guid UniqueId { get; set; }
        public int AreaId { get; set; }
        public string AreaName { get; set; }
        public Nullable<int> CityId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_City MAS_City { get; set; }
    }
}
