//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_ChefOrder
    {
        public System.Guid UniqueId { get; set; }
        public int ChefOrderId { get; set; }
        public System.DateTime OrderGivenDatetime { get; set; }
        public System.TimeSpan ChefDeliveredDateTime { get; set; }
        public System.DateTime AssignedPickUpDate { get; set; }
        public System.TimeSpan AssignedPickUpTime { get; set; }
        public int TaskStatusID { get; set; }
        public bool IsDeleted { get; set; }
    }
}
