//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_ChefDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRN_ChefDetails()
        {
            this.TRN_ChefOtherDetails = new HashSet<TRN_ChefOtherDetails>();
            this.TRN_MapOrderToChef = new HashSet<TRN_MapOrderToChef>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int ChefId { get; set; }
        public string ChefFullName { get; set; }
        public int ChefTypeId { get; set; }
        public string MobileNumber { get; set; }
        public string AlternateMobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public int CityId { get; set; }
        public string AreaName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int UserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_ChefType MAS_ChefType { get; set; }
        public virtual MAS_City MAS_City { get; set; }
        public virtual TRN_UserDetail TRN_UserDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_ChefOtherDetails> TRN_ChefOtherDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_MapOrderToChef> TRN_MapOrderToChef { get; set; }
    }
}
