//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_UserAddressDetails
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRN_UserAddressDetails()
        {
            this.TRN_DeliveryDetails = new HashSet<TRN_DeliveryDetails>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int AddressDetailId { get; set; }
        public int UserId { get; set; }
        public int AddressTypeID { get; set; }
        public int DeliveryPointId { get; set; }
        public string AreaName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int CityId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_AddressType MAS_AddressType { get; set; }
        public virtual MAS_City MAS_City { get; set; }
        public virtual MAS_DeliveryLocation MAS_DeliveryLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_DeliveryDetails> TRN_DeliveryDetails { get; set; }
        public virtual TRN_UserDetail TRN_UserDetail { get; set; }
    }
}
