//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_UserRights
    {
        public System.Guid UniqueId { get; set; }
        public int Id { get; set; }
        public int Userid { get; set; }
        public int RightsId { get; set; }
        public string Password { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_Rights MAS_Rights { get; set; }
        public virtual TRN_UserDetail TRN_UserDetail { get; set; }
    }
}
