//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRN_Order()
        {
            this.TRN_DeliveryDetails = new HashSet<TRN_DeliveryDetails>();
            this.TRN_MapOrderToChef = new HashSet<TRN_MapOrderToChef>();
            this.TRN_MealPackProcessing = new HashSet<TRN_MealPackProcessing>();
            this.TRN_OrderDetails = new HashSet<TRN_OrderDetails>();
            this.TRN_OrderAppliedDiscount = new HashSet<TRN_OrderAppliedDiscount>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int OrderTypeId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<System.DateTime> OrderCreatedDatetime { get; set; }
        public int PaymentTypeId { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> ActualPrice { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> TotalDiscount { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_OrderStatus MAS_OrderStatus { get; set; }
        public virtual MAS_OrderType MAS_OrderType { get; set; }
        public virtual MAS_PaymentType MAS_PaymentType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_DeliveryDetails> TRN_DeliveryDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_MapOrderToChef> TRN_MapOrderToChef { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_MealPackProcessing> TRN_MealPackProcessing { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_OrderDetails> TRN_OrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRN_OrderAppliedDiscount> TRN_OrderAppliedDiscount { get; set; }
        public virtual TRN_UserDetail TRN_UserDetail { get; set; }
    }
}
