//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_OrderAppliedDiscount
    {
        public System.Guid UniqueId { get; set; }
        public int AppliedDiscountId { get; set; }
        public int DiscountId { get; set; }
        public int SpecialDiscountId { get; set; }
        public bool IsDeleted { get; set; }
        public int OrderId { get; set; }
    
        public virtual MAS_Discount MAS_Discount { get; set; }
        public virtual TRN_Order TRN_Order { get; set; }
        public virtual TRN_SpecialDiscount TRN_SpecialDiscount { get; set; }
    }
}
