//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [ModelMetadataType(typeof(MAS_RightsMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(TRN_GroupRights))]
    [KnownType(typeof(TRN_UserRights))]
    public partial class MAS_Rights  :BusinessEntityBase 
    {
    public MAS_Rights()
    {
    this.TRN_GroupRights = new HashSet<TRN_GroupRights>();
    this.TRN_UserRights = new HashSet<TRN_UserRights>();
    }
    
    [DataMember]
    public System.Guid UniqueId { get; set; }
    [DataMember]
    public int Id { get; set; }
    [DataMember]
    public string Rights { get; set; }
    [DataMember]
    public bool IsDeleted { get; set; }
    
    [DataMember]
    public virtual ICollection<TRN_GroupRights> TRN_GroupRights { get; set; }
    [DataMember]
    public virtual ICollection<TRN_UserRights> TRN_UserRights { get; set; }
    }
    
}
