//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [ModelMetadataType(typeof(MAS_AreaMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_City))]
    public partial class MAS_Area  :BusinessEntityBase 
    {
     [DataMember]
    public System.Guid UniqueId { get; set; }
     [Key()]
     [DataMember]
    public int AreaId { get; set; }
     [DataMember]
    public string AreaName { get; set; }
     [DataMember]
    public Nullable<int> CityId { get; set; }
     [DataMember]
    public bool IsDeleted { get; set; }
    
    [DataMember]
    public virtual MAS_City MAS_City { get; set; }
    }
    
}
