//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [ModelMetadataType(typeof(MAS_RoleMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(TRN_GroupRights))]
    [KnownType(typeof(TRN_UserDetail))]
    public partial class MAS_Role  :BusinessEntityBase 
    {
    public MAS_Role()
    {
    this.TRN_GroupRights = new HashSet<TRN_GroupRights>();
    this.TRN_UserDetail = new HashSet<TRN_UserDetail>();
    }
    
    [DataMember]
    public System.Guid UniqueId { get; set; }
    [DataMember]
    public int RoleId { get; set; }
    [DataMember]
    public string RoleName { get; set; }
    [DataMember]
    public bool IsDeleted { get; set; }
    
    [DataMember]
    public virtual ICollection<TRN_GroupRights> TRN_GroupRights { get; set; }
    [DataMember]
    public virtual ICollection<TRN_UserDetail> TRN_UserDetail { get; set; }
    }
    
}
