//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Common;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;


namespace DotnetCore.Business.Entities
{
    [ModelMetadataType(typeof(TRN_GroupRightsMetadata))]
    [DataContract(IsReference = true)]
    [KnownType(typeof(MAS_Rights))]
    [KnownType(typeof(MAS_Role))]
    public partial class TRN_GroupRights  :BusinessEntityBase 
    {
    [DataMember]
    public System.Guid UniqueId { get; set; }
    [DataMember]
    public int Id { get; set; }
    [DataMember]
    public int RoleId { get; set; }
    [DataMember]
    public int RightsId { get; set; }
    [DataMember]
    public string Password { get; set; }
    [DataMember]
    public bool IsDeleted { get; set; }
    
    [DataMember]
    public virtual MAS_Rights MAS_Rights { get; set; }
    [DataMember]
    public virtual MAS_Role MAS_Role { get; set; }
    }
    
}
