//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CategoryDto
    {
        public MAS_CategoryDto()
        {
            this.MAS_FoodDto = new HashSet<MAS_FoodDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int CategoryId { get; set; }
        public string Name { get; set; }
        public string Descriptions { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<MAS_FoodDto> MAS_FoodDto { get; set; }
    }
}
