//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_DeliveryLocationDto
    {
        public MAS_DeliveryLocationDto()
        {
            this.TRN_DeliveryDetailsDto = new HashSet<TRN_DeliveryDetailsDto>();
            this.TRN_UserAddressDetailsDto = new HashSet<TRN_UserAddressDetailsDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int DeliveyPointId { get; set; }
        public string DeliveryPointName { get; set; }
        public int AreaId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<TRN_DeliveryDetailsDto> TRN_DeliveryDetailsDto { get; set; }
        public virtual ICollection<TRN_UserAddressDetailsDto> TRN_UserAddressDetailsDto { get; set; }
    }
}
