//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_AddressTypeDto
    {
        public MAS_AddressTypeDto()
        {
            this.TRN_UserAddressDetailsDto = new HashSet<TRN_UserAddressDetailsDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int AddressTypeId { get; set; }
        public string AddressType { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<TRN_UserAddressDetailsDto> TRN_UserAddressDetailsDto { get; set; }
    }
}
