//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_DiscountDto
    {
        public MAS_DiscountDto()
        {
            this.TRN_OrderAppliedDiscountDto = new HashSet<TRN_OrderAppliedDiscountDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int DiscountId { get; set; }
        public string DiscountName { get; set; }
        public Nullable<int> FoodId { get; set; }
        public Nullable<int> DiscountTypeID { get; set; }
        public int DiscountPrice { get; set; }
        public int DiscountPercentage { get; set; }
        public System.DateTime ValidityFrom { get; set; }
        public System.DateTime ValidityTo { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_DiscountTypeDto MAS_DiscountTypeDto { get; set; }
        public virtual MAS_FoodDto MAS_FoodDto { get; set; }
        public virtual ICollection<TRN_OrderAppliedDiscountDto> TRN_OrderAppliedDiscountDto { get; set; }
    }
}
