//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_RightsDto
    {
        public MAS_RightsDto()
        {
            this.TRN_GroupRightsDto = new HashSet<TRN_GroupRightsDto>();
            this.TRN_UserRightsDto = new HashSet<TRN_UserRightsDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int Id { get; set; }
        public string Rights { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual ICollection<TRN_GroupRightsDto> TRN_GroupRightsDto { get; set; }
        public virtual ICollection<TRN_UserRightsDto> TRN_UserRightsDto { get; set; }
    }
}
