//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_MealPackDto
    {
        public MAS_MealPackDto()
        {
            this.TRN_MealPackMappingDto = new HashSet<TRN_MealPackMappingDto>();
            this.TRN_MealPackProcessingDto = new HashSet<TRN_MealPackProcessingDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int MealPackId { get; set; }
        public string MealPackName { get; set; }
        public string Descriptions { get; set; }
        public int TotalMealCount { get; set; }
        public int CurrentMealCount { get; set; }
        public int CurrentPrice { get; set; }
        public int TotalPrice { get; set; }
        public int GSTPrice { get; set; }
        public int GSTPercentage { get; set; }
        public int OrderTypeId { get; set; }
        public Nullable<int> OrderTypeCode { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_OrderTypeDto MAS_OrderTypeDto { get; set; }
        public virtual ICollection<TRN_MealPackMappingDto> TRN_MealPackMappingDto { get; set; }
        public virtual ICollection<TRN_MealPackProcessingDto> TRN_MealPackProcessingDto { get; set; }
    }
}
