//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObserveDto
    {
        public int ObserveId { get; set; }
        public string TableName { get; set; }
        public bool Changed { get; set; }
        public bool IsDeleted { get; set; }
    }
}
