//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_MealPackProcessingDto
    {
        public System.Guid UniqueId { get; set; }
        public int MealPackProcessingId { get; set; }
        public int MealPackId { get; set; }
        public int TotalMealCount { get; set; }
        public int UsedMealCount { get; set; }
        public int RemainingMealCount { get; set; }
        public System.DateTime ScheduleDates { get; set; }
        public int UserId { get; set; }
        public int OrderId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_MealPackDto MAS_MealPackDto { get; set; }
        public virtual TRN_OrderDto TRN_OrderDto { get; set; }
        public virtual TRN_UserDetailDto TRN_UserDetailDto { get; set; }
    }
}
