//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_SpecialDiscountDto
    {
        public TRN_SpecialDiscountDto()
        {
            this.TRN_OrderAppliedDiscountDto = new HashSet<TRN_OrderAppliedDiscountDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int SpecialDiscountId { get; set; }
        public string DiscountName { get; set; }
        public int DiscountTypeID { get; set; }
        public string Descriptions { get; set; }
        public int UserId { get; set; }
        public bool IsDiscountUsed { get; set; }
        public int DiscountPrice { get; set; }
        public int DiscountPercentage { get; set; }
        public Nullable<System.DateTime> ValidityFrom { get; set; }
        public Nullable<System.DateTime> ValidityTo { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_DiscountTypeDto MAS_DiscountTypeDto { get; set; }
        public virtual ICollection<TRN_OrderAppliedDiscountDto> TRN_OrderAppliedDiscountDto { get; set; }
        public virtual TRN_UserDetailDto TRN_UserDetailDto { get; set; }
    }
}
