//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_ChefDetailsDto
    {
        public TRN_ChefDetailsDto()
        {
            this.TRN_ChefOtherDetailsDto = new HashSet<TRN_ChefOtherDetailsDto>();
            this.TRN_MapOrderToChefDto = new HashSet<TRN_MapOrderToChefDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int ChefId { get; set; }
        public string ChefFullName { get; set; }
        public int ChefTypeId { get; set; }
        public string MobileNumber { get; set; }
        public string AlternateMobileNumber { get; set; }
        public string PhoneNumber { get; set; }
        public string EmailId { get; set; }
        public int CityId { get; set; }
        public string AreaName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int UserId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_ChefTypeDto MAS_ChefTypeDto { get; set; }
        public virtual MAS_CityDto MAS_CityDto { get; set; }
        public virtual TRN_UserDetailDto TRN_UserDetailDto { get; set; }
        public virtual ICollection<TRN_ChefOtherDetailsDto> TRN_ChefOtherDetailsDto { get; set; }
        public virtual ICollection<TRN_MapOrderToChefDto> TRN_MapOrderToChefDto { get; set; }
    }
}
