//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_OrderDto
    {
        public TRN_OrderDto()
        {
            this.TRN_DeliveryDetailsDto = new HashSet<TRN_DeliveryDetailsDto>();
            this.TRN_MapOrderToChefDto = new HashSet<TRN_MapOrderToChefDto>();
            this.TRN_MealPackProcessingDto = new HashSet<TRN_MealPackProcessingDto>();
            this.TRN_OrderDetailsDto = new HashSet<TRN_OrderDetailsDto>();
            this.TRN_OrderAppliedDiscountDto = new HashSet<TRN_OrderAppliedDiscountDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int OrderId { get; set; }
        public int UserId { get; set; }
        public int OrderTypeId { get; set; }
        public int OrderStatusId { get; set; }
        public Nullable<System.DateTime> OrderCreatedDatetime { get; set; }
        public int PaymentTypeId { get; set; }
        public Nullable<int> TotalQuantity { get; set; }
        public Nullable<int> ActualPrice { get; set; }
        public Nullable<int> TotalPrice { get; set; }
        public Nullable<int> TotalDiscount { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_OrderStatusDto MAS_OrderStatusDto { get; set; }
        public virtual MAS_OrderTypeDto MAS_OrderTypeDto { get; set; }
        public virtual MAS_PaymentTypeDto MAS_PaymentTypeDto { get; set; }
        public virtual ICollection<TRN_DeliveryDetailsDto> TRN_DeliveryDetailsDto { get; set; }
        public virtual ICollection<TRN_MapOrderToChefDto> TRN_MapOrderToChefDto { get; set; }
        public virtual ICollection<TRN_MealPackProcessingDto> TRN_MealPackProcessingDto { get; set; }
        public virtual ICollection<TRN_OrderDetailsDto> TRN_OrderDetailsDto { get; set; }
        public virtual ICollection<TRN_OrderAppliedDiscountDto> TRN_OrderAppliedDiscountDto { get; set; }
        public virtual TRN_UserDetailDto TRN_UserDetailDto { get; set; }
    }
}
