//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_UserAddressDetailsDto
    {
        public TRN_UserAddressDetailsDto()
        {
            this.TRN_DeliveryDetailsDto = new HashSet<TRN_DeliveryDetailsDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int AddressDetailId { get; set; }
        public int UserId { get; set; }
        public int AddressTypeID { get; set; }
        public int DeliveryPointId { get; set; }
        public string AreaName { get; set; }
        public string AddressLine1 { get; set; }
        public string AddressLine2 { get; set; }
        public int CityId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_AddressTypeDto MAS_AddressTypeDto { get; set; }
        public virtual MAS_CityDto MAS_CityDto { get; set; }
        public virtual MAS_DeliveryLocationDto MAS_DeliveryLocationDto { get; set; }
        public virtual ICollection<TRN_DeliveryDetailsDto> TRN_DeliveryDetailsDto { get; set; }
        public virtual TRN_UserDetailDto TRN_UserDetailDto { get; set; }
    }
}
