//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_MapOrderToChefDto
    {
        public System.Guid UniqueId { get; set; }
        public int MapOrderID { get; set; }
        public int OrderId { get; set; }
        public int ChefId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual TRN_ChefDetailsDto TRN_ChefDetailsDto { get; set; }
        public virtual TRN_OrderDto TRN_OrderDto { get; set; }
    }
}
