//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_UserDetailDto
    {
        public TRN_UserDetailDto()
        {
            this.TRN_ChefDetailsDto = new HashSet<TRN_ChefDetailsDto>();
            this.TRN_MealPackProcessingDto = new HashSet<TRN_MealPackProcessingDto>();
            this.TRN_OrderDto = new HashSet<TRN_OrderDto>();
            this.TRN_SpecialDiscountDto = new HashSet<TRN_SpecialDiscountDto>();
            this.TRN_UserAddressDetailsDto = new HashSet<TRN_UserAddressDetailsDto>();
            this.TRN_UserRightsDto = new HashSet<TRN_UserRightsDto>();
        }
    
        public System.Guid UniqueId { get; set; }
        public int UserId { get; set; }
        public string Name { get; set; }
        public string EmailId { get; set; }
        public string PhoneNo { get; set; }
        public int RoleId { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_RoleDto MAS_RoleDto { get; set; }
        public virtual ICollection<TRN_ChefDetailsDto> TRN_ChefDetailsDto { get; set; }
        public virtual ICollection<TRN_MealPackProcessingDto> TRN_MealPackProcessingDto { get; set; }
        public virtual ICollection<TRN_OrderDto> TRN_OrderDto { get; set; }
        public virtual ICollection<TRN_SpecialDiscountDto> TRN_SpecialDiscountDto { get; set; }
        public virtual ICollection<TRN_UserAddressDetailsDto> TRN_UserAddressDetailsDto { get; set; }
        public virtual ICollection<TRN_UserRightsDto> TRN_UserRightsDto { get; set; }
    }
}
