//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Neeyamo.Business.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRN_ChefOtherDetailsDto
    {
        public System.Guid UniqueId { get; set; }
        public int ChefOtherDetailID { get; set; }
        public int ChefId { get; set; }
        public int FoodTypeId { get; set; }
        public string SpecialistAt { get; set; }
        public string Descriptions { get; set; }
        public Nullable<int> AvaiableDays { get; set; }
        public string AvailableTime { get; set; }
        public bool AvaiableForLunch { get; set; }
        public bool AvailableForDinner { get; set; }
        public bool IsDeleted { get; set; }
    
        public virtual MAS_FoodTypeDto MAS_FoodTypeDto { get; set; }
        public virtual TRN_ChefDetailsDto TRN_ChefDetailsDto { get; set; }
    }
}
