//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.EF.Tool.Persistance
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using Neeyamo.Business.Entities;
    
    public partial class HomeFoodEntities : DbContext
    {
        public HomeFoodEntities()
            : base("name=HomeFoodEntities")
        {
    	 //this.SetCommandTimeOut(500);
    	 // this.Database.Connection.ConnectionString = connString; 
        }
    
        public System.Data.Entity.Core.Objects.ObjectContext ObjectContext
        {
            get { return ((IObjectContextAdapter)this).ObjectContext; }
        }
    
    	
        public System.Data.Entity.Core.Objects.ObjectContext ObjectContextDynamic
        {
           get
    		{ 
    			this.Database.CommandTimeout = 120;
    			return ((IObjectContextAdapter)this).ObjectContext; 
    		}
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<MAS_AddressType> MAS_AddressType { get; set; }
        public DbSet<MAS_Category> MAS_Category { get; set; }
        public DbSet<MAS_ChefType> MAS_ChefType { get; set; }
        public DbSet<MAS_City> MAS_City { get; set; }
        public DbSet<MAS_DeliveryLocation> MAS_DeliveryLocation { get; set; }
        public DbSet<MAS_Discount> MAS_Discount { get; set; }
        public DbSet<MAS_DiscountType> MAS_DiscountType { get; set; }
        public DbSet<MAS_Food> MAS_Food { get; set; }
        public DbSet<MAS_FoodType> MAS_FoodType { get; set; }
        public DbSet<MAS_MealPack> MAS_MealPack { get; set; }
        public DbSet<MAS_OrderStatus> MAS_OrderStatus { get; set; }
        public DbSet<MAS_OrderType> MAS_OrderType { get; set; }
        public DbSet<MAS_PaymentType> MAS_PaymentType { get; set; }
        public DbSet<MAS_Price> MAS_Price { get; set; }
        public DbSet<MAS_Rights> MAS_Rights { get; set; }
        public DbSet<MAS_Role> MAS_Role { get; set; }
        public DbSet<Observe> Observe { get; set; }
        public DbSet<TRN_ChefDetails> TRN_ChefDetails { get; set; }
        public DbSet<TRN_ChefOrder> TRN_ChefOrder { get; set; }
        public DbSet<TRN_ChefOtherDetails> TRN_ChefOtherDetails { get; set; }
        public DbSet<TRN_DeliveryDetails> TRN_DeliveryDetails { get; set; }
        public DbSet<TRN_GroupRights> TRN_GroupRights { get; set; }
        public DbSet<TRN_MapOrderToChef> TRN_MapOrderToChef { get; set; }
        public DbSet<TRN_MealPackMapping> TRN_MealPackMapping { get; set; }
        public DbSet<TRN_MealPackProcessing> TRN_MealPackProcessing { get; set; }
        public DbSet<TRN_Order> TRN_Order { get; set; }
        public DbSet<TRN_OrderAppliedDiscount> TRN_OrderAppliedDiscount { get; set; }
        public DbSet<TRN_OrderDetails> TRN_OrderDetails { get; set; }
        public DbSet<TRN_SpecialDiscount> TRN_SpecialDiscount { get; set; }
        public DbSet<TRN_UserAddressDetails> TRN_UserAddressDetails { get; set; }
        public DbSet<TRN_UserDetail> TRN_UserDetail { get; set; }
        public DbSet<TRN_UserPassword> TRN_UserPassword { get; set; }
        public DbSet<TRN_UserRights> TRN_UserRights { get; set; }
    }
}
